controller_manager:
  ros__parameters:
    update_rate: 1000  # 控制器更新频率
    
    # 控制器列表
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    # mecanum_drive_controller:
    #   type: mecanum_drive_controller/MecanumDriveController

# 关节状态广播器配置
joint_state_broadcaster:
  ros__parameters:
    joints:
      - fr_wheel_joint  # 前右轮
      - fl_wheel_joint  # 前左轮  
      - rr_wheel_joint  # 后右轮
      - rl_wheel_joint  # 后左轮
    interfaces:
      - position
      - velocity

# 麦卡纳姆轮驱动控制器配置
# mecanum_drive_controller:
#   ros__parameters:
#     # 轮子关节名称
#     front_left_wheel_joint: "fl_wheel_joint"
#     front_right_wheel_joint: "fr_wheel_joint" 
#     rear_left_wheel_joint: "rl_wheel_joint"
#     rear_right_wheel_joint: "rr_wheel_joint"
    
#     # 物理参数（根据您的 Gazebo 插件配置）
#     wheel_separation_width: 0.447   # 左右轮距 (m)
#     wheel_separation_length: 0.383  # 前后轮距 (m) 
#     wheel_radius: 0.065             # 轮子半径 (m)
    
#     # 坐标系配置
#     base_frame_id: "base_footprint"
#     odom_frame_id: "odom"
    
#     # 发布频率
#     publish_rate: 50.0
    
#     # 使能里程计tf变换
#     enable_odom_tf: true
    
#     # 速度和加速度限制
#     linear:
#       x:
#         max_velocity: 2.0        # 最大线速度 (m/s)
#         max_acceleration: 1.0    # 最大线加速度 (m/s²)
#       y:
#         max_velocity: 2.0
#         max_acceleration: 1.0
#     angular:
#       z:
#         max_velocity: 3.14       # 最大角速度 (rad/s)
#         max_acceleration: 1.57   # 最大角加速度 (rad/s²)
    
#     # 命令接口类型
#     interface_name: velocity
    
#     # 超时设置
#     cmd_vel_timeout: 0.5  # 命令超时时间 (s)